door_display:
  # use random value here
  # import os; print(os.urandom(16)) works to generate it
  secretkey: abcdefghijklmnop

  # MQTT broker hostname
  broker: localhost
  doorname: front_door
  topicname: esp-rfid
  
  # How long to leave stuff on the screen after a scan.
  dwell_time: 15

  logfile: display.log