system:
  logfile: tcdoor.log
  database: dooraccess.db
  email_alerts: #we can setup an email alert if a critical error of any kind is encountered
    host: smtp.gmail.com
    port: 587
    from_addr: door@example.com
    to_addrs:
      - it@example.com
      - manager@example.com
    subject: Door Controller Failure
    smtp_user: user@gmail.com
    smtp_pass: abcdefg
    level: critical # one of critical, fatal, error, warning
webpanel:
  # Use random value here
  # import os; print(os.urandom(16)) works to generate it
  secretkey: abcdefghijklmnopqrstuvwxyz
  # Change me
  username: tcmaker
  password: hackfactory


auth:
  tcmaker:
    dbfile: tcmaker-membership.db
    url: https://members.tcmaker.org/api/v1/keyfobs/
    api_key: 1234567890abcdefg
    refresh: 20

scanners:
  # Format
  # scannername: - name of the scanner
  #   board: resource name of the board, e.g. "ftdi://ftdi:232:AM01QC8Q/1"
  #          resource names can be found via TODO
  #   scanner: scanner's index on the board.
  #
  # Example:
  #
  # frontdoorscanner:
  #   board: &aliasname "ftdi://ftdi:232/A123456/1"
  #   scanner: 1

  frontscanner:
    board: &accxboard "ftdi://ftdi:232:AM01QC8Q/1"
    scanner: 1

  rearscanner:
    board: *accxboard
    scanner: 2

facilities:
  # Format
  # facilityname: - name of the facility
  #   board: resource name of the board, same as scanners
  #   scanner: NAME of scanner to use to grant access to the facility
  #   outscanner: [Optional] NAME of scanner to use to signify exiting/finishing with the facility
  #   relay: index of the relay to activate to unlock access to the facility
  #   duration: [Optional] duration in floating point seconds to energize the relay
  #
  # Example:
  #
  # frontdoor:
  #   board: &aliasname
  #   scanner: frontdoorscanner
  #   outscanner: exitscanner
  #   relay: 1
  #   duration: 5

  frontdoor:
    board: *accxboard
    scanner: frontscanner
    relay: 1

  laser:
    board: *accxboard
    scanner: rearscanner
    relay: 2

