accx_hw:
  broker: localhost #defaults to mosquito
  fob_database: fobs.db #defaults to fobs.db
  board: "ftdi://ftdi:232:AM01QCWE/1"
  name: front_door
  topicname: esp-rfid
  logfile: accx_log.log


