hardware_service:
  name: frontdoor
  listen: tcp://0.0.0.0:3119 #defaults to this
  key: .networkkey
  #listen: unix:///tmp/bba

  # remote authorization and coordination server
  auth: http://127.0.0.1:8443
  devices:
    accxboard: "ftdi://ftdi:232:AM01QCWE/1"
    anotherboard: "awesome"



