
CONFIG_NOT_FOUND = 5
INVALID_CONFIG = 6
KEY_MISSING = 7
KEY_EMPTY = 13
KEY_BAD_PERMISSIONS = 14
CONFIG_SECTION_MISSING = 8
NO_LISTEN_ADDRESS = 9
INVALID_LISTEN_ADDRESS = 10
SOCKET_NOT_FOUND = 11
SOCKET_PATH_NOT_A_SOCKET = 12
NO_AUTH_URL = 15
INSTANCE_ALREADY_RUNNING = 1
